### ISSUE TITLE
Data type in sd file?

### ISSUE THREAD

**Issue by dunk8888** [JensAndree/Glediator-from-sdcard#2]
Hi,what kind of data is in the file? is it like this 225,222,234,11, etc ?Reason i ask is ive been trying to do something like this my self,i can make patterns with an editor and the data produced is bytes of data like above,is that what glediator outputs to the file to be played?

Also do you think it will be possible to get adafruits neopixel library to do the same? if so what part would i put in place of this  fxdata.readBytes((char*)leds, NUM_LEDS*3); any help would be great,i just want to be able to store patterns to sd and play them back,but i dont use glediator. I was going to use flash storage but ime only a beginer to coding and found it very confusing to read bytes from flash so i opted for sd for ease of use.Or do you have an example file i could use.thanks

**Comment by JensAndree** [comment]
I had to look at a recorded file because it's such a long time ago I made this project but it's basically just a continuous stream of byte triplets. With triplets I mean you read three bytes for each led.

I don't use Adafruits Neopixel library because I've written my own that I think is better - for how I use rgb leds anyway, but by using the function .setPixelColor() I think it's easy to modify my Glediator-from-sdcard to use Neopixel library. All my script does is to read byte values from a file (written by Glediator) and used as colour data.

Play around with .setPixelColor() in Neopixel library. If Neopixel doesn't use byte values you might have to convert them into something usable there, but it shouldn't be too complicated.

I've attached an example file that I made a long time ago but it's basically just a stream of bytes.

[plasma2-rec.txt](https://github.com/JensAndree/Glediator-from-sdcard/files/1429009/plasma2-rec.txt)
